### ISSUE TITLE
After checking remote in HomeKit, it prompts: Unknown error occurred

### ISSUE THREAD

**Issue by ren9821** [home-assistant/home-assistant.io#17431]
### Feedback

This problem will occur when upgrading from 2021.3.4 to 2021.4.0-2021.4.4

Logger: aiohttp.server
Source: components/homekit/util.py:510 
First occurred: 下午1:41:51 (2 occurrences) 
Last logged: 下午1:41:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/homekit/config_flow.py", line 148, in async_step_pairing
    await self._async_add_entries_for_accessory_mode_entities(port)
  File "/usr/src/homeassistant/homeassistant/components/homekit/config_flow.py", line 168, in _async_add_entries_for_accessory_mode_entities
    accessory_mode_entity_ids = _async_get_entity_ids_for_accessory_mode(
  File "/usr/src/homeassistant/homeassistant/components/homekit/config_flow.py", line 484, in _async_get_entity_ids_for_accessory_mode
    return [
  File "/usr/src/homeassistant/homeassistant/components/homekit/config_flow.py", line 487, in <listcomp>
    if state_needs_accessory_mode(state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/util.py", line 510, in state_needs_accessory_mode
    and state.attributes.get(ATTR_SUPPORTED_FEATURES) & SUPPORT_ACTIVITY
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2021.4.4

**Comment by Jc2k** [comment]
Hello. This traceback looks like a `homekit` issue rather than a `homekit_controller` issue. I will reassign it to the right area for you.
