### ISSUE TITLE
Toon integration problem with engie

### ISSUE THREAD

**Issue by bLackCat-79** [home-assistant/home-assistant.io#18387]
### Feedback

I configurated my toon api key in the configurations.xml file, I see the integration but when it needs to connect to the callback API URL I get this: 
![afbeelding](https://user-images.githubusercontent.com/56641399/124384089-18a97880-dcd0-11eb-8fc2-20526e45a10a.png)

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2021.6.6

**Comment by frenck** [comment]
Anything in the logs?

**Comment by bLackCat-79** [comment]
Can you tell me what log file you need?

**Comment by bLackCat-79** [comment]
I don't see anything in the logs, the forward URL is: https://api.toon.eu/authorize?response_type=code&client_id=AJAAECvieQxdAPR72naAzh2GfzCnu5Gi&redirect_uri=https://home-assistant.telkom.be/auth/external/callback&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiOWU2Yjk5OGVlYzViNDQ3ZDllMTA5ZTFjZGNhMTQyOTUiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2hvbWUtYXNzaXN0YW50LnRlbGtvbS5iZS9hdXRoL2V4dGVybmFsL2NhbGxiYWNrIn0.UL20S12Nl4gIENRF7giqpr9xEryJ8h1Dujj1dlh6QkQ&tenant_id=electrabel&error=true

**Comment by frenck** [comment]
> Can you tell me what log file you need?

The Home Assistant log file.

**Comment by bLackCat-79** [comment]
Nothing in log files.
I just click on configure 
![afbeelding](https://user-images.githubusercontent.com/56641399/124496782-29361d80-ddba-11eb-939f-ece54914e839.png)
Then open website
![afbeelding](https://user-images.githubusercontent.com/56641399/124496827-3e12b100-ddba-11eb-81a1-2cb7987a88a6.png)
I enter my account details, but it seems toon API is not making a correct callback or something

**Comment by bLackCat-79** [comment]
https://community.home-assistant.io/t/toon-integration-for-belgian-engie-electrabel-boxx/313616/7

It seems I am not the ony one with this problem

**Comment by frenck** [comment]
The discussion in the forums shows a recent change that caused this, however, the Home Assistant Toon integration hasn't had any updates in that timeframe specified.

The upstream documentation is also unchanged: <https://developer.toon.eu/authentication>

As I am not an Engie user myself (but an Eneco/Toon user), I cannot help in resolving the issue and would rely on a contribution.

**Comment by bLackCat-79** [comment]
If you can tell me what I need to do, I am willing to help?

**Comment by bLackCat-79** [comment]
@frenck I can even give you ssh access to my HA if you want?

**Comment by frenck** [comment]
That is not what is needed. What needs to debug the OAuth flow for the Toon integration with Engie, this would need knowledge of setting up a development environment for Home Assistant, knowing Python and knowing how to use a debugger.

**Comment by bLackCat-79** [comment]
I can give you a develop machine?

**Comment by bLackCat-79** [comment]
When I click on open website it goes to this URL:

https://api.toon.eu/authorize?response_type=code&client_id=AJAAECvieQxdAPR72naAzh2GfzCnu5Gi&redirect_uri=https://home-assistant.telkom.be/auth/external/callback&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiOWU2Yjk5OGVlYzViNDQ3ZDllMTA5ZTFjZGNhMTQyOTUiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2hvbWUtYXNzaXN0YW50LnRlbGtvbS5iZS9hdXRoL2V4dGVybmFsL2NhbGxiYWNrIn0.UL20S12Nl4gIENRF7giqpr9xEryJ8h1Dujj1dlh6QkQ&tenant_id=electrabel

if I change the url to:

https://api.toon.eu/toonapi-accesstoken?tenant_id=electrabel&client_id=AJAAECvieQxdAPR72naAzh2GfzCnu5Gi&redirect_uri=https://home-assistant.telkom.be/auth/external/callback&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiOWU2Yjk5OGVlYzViNDQ3ZDllMTA5ZTFjZGNhMTQyOTUiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL2hvbWUtYXNzaXN0YW50LnRlbGtvbS5iZS9hdXRoL2V4dGVybmFsL2NhbGxiYWNrIn0.UL20S12Nl4gIENRF7giqpr9xEryJ8h1Dujj1dlh6QkQ&tenant_id=electrabel

I login and see this:

![afbeelding](https://user-images.githubusercontent.com/56641399/124577574-afe80a80-de4d-11eb-9210-6854db2b14e5.png)

How do I put this access token in HA?

**Comment by bLackCat-79** [comment]
My guess is that the callback url needs to be in a different syntax

**Comment by bLackCat-79** [comment]
I don't know if this is related, but I saw this in my log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 468, in _handle
    match_info = await self._router.resolve(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py", line 1004, in resolve
    match_dict, allowed = await resource.resolve(request)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 540, in resolve
    and request.url.parts[1] not in self.hass.data[DATA_PANELS]
IndexError: tuple index out of range

**Comment by bLackCat-79** [comment]
Maybe I should just enter the token to my configuration.yml?
Can you tell me what tag @frenck ?
toon:
  client_id: 
  client_secret:

**Comment by frenck** [comment]
> How do I put this access token in HA?

That is a different authentication method, and only applies to Eneco users. Additionally, that authentication method is not used by this integration.

**Comment by bLackCat-79** [comment]
But I cannot add the access token to my configuration.yml? Correct? @frenck

**Comment by frenck** [comment]
That is what I said.

**Comment by bLackCat-79** [comment]
Anyone else who can help?
