### ISSUE TITLE
Error while creating backup

### ISSUE THREAD

**Issue by Krandelbord** [home-assistant/home-assistant.io#29675]
### Feedback

I have home assistant installed on docker in x86 machine.
When I press cerate backup button. I can see in docker logs the following stacktrace

`2023-11-02 22:41:00.397 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140355756237888] Error handling message: Unknown error (unknown_error) Emilian from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/backup/websocket.py", line 70, in handle_create
    backup = await manager.generate_backup()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/backup/manager.py", line 176, in generate_backup
    raise result
  File "/usr/src/homeassistant/homeassistant/components/zha/backup.py", line 15, in async_pre_backup
    zha_gateway = get_zha_gateway(hass)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/core/helpers.py", line 446, in get_zha_gateway
    raise ValueError("No gateway object exists")
ValueError: No gateway object exists
2023-11-02 22:42:10.482 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140355756237888] Error handling message: Unknown error (unknown_error) Emilian from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/backup/websocket.py", line 70, in handle_create
    backup = await manager.generate_backup()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/backup/manager.py", line 176, in generate_backup
    raise result
  File "/usr/src/homeassistant/homeassistant/components/zha/backup.py", line 15, in async_pre_backup
    zha_gateway = get_zha_gateway(hass)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/core/helpers.py", line 446, in get_zha_gateway
    raise ValueError("No gateway object exists")
ValueError: No gateway object exists
`

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2023.10.5

**Comment by marc-gist** [comment]
I am getting very similar errors on 2023.11.0

**Comment by Hedda** [comment]
@Krandelbord @marc-gist This is a GitHub repo for documention and not the right place to ask for support or report bugs. This repo is only for reporting incorrect or missing information on the websites, and not get help with problems or bugs. See:

https://www.home-assistant.io/help/

You should instead ask for help in the in the community forum or Discord Chat Server and report any bugs as issues to the Home Assistant core repository (and if possible add the correct integration there if the issue is just with a specific integration):

https://community.home-assistant.io/ -> select matching section and subsection -> New Topic

https://github.com/home-assistant/core/issues (New issue -> Report an issue with Home Assistant Core
