### ISSUE TITLE
ecobee won't install

### ISSUE THREAD

**Issue by jasongold** [home-assistant/home-assistant.io#415]
I don't have a PIN and it isn't generating one for me.

Here is the error I get:
```
16-04-22 02:59:48 homeassistant.bootstrap: Error during setup of component ecobee
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/bootstrap.py", line 158, in _setup_component
    if not component.setup(hass, config):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/ecobee.py", line 130, in setup
    NETWORK = EcobeeData(hass.config.path(ECOBEE_CONFIG_FILE))
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/ecobee.py", line 99, in __init__
    self.ecobee = Ecobee(config_file)
  File "/home/pi/.homeassistant/deps/pyecobee/__init__.py", line 53, in __init__
    self.request_pin()
  File "/home/pi/.homeassistant/deps/pyecobee/__init__.py", line 64, in request_pin
    self.authorization_code = request.json()['code']
KeyError: 'code'
```

**Comment by fabaff** [comment]
This is the repository for the documentation, please open an issue [here](https://github.com/home-assistant/home-assistant/issues/new) or use the [forum](https://community.home-assistant.io/).
