### ISSUE TITLE
[OS X] nmap_tracker only works with hass --open-ui, throws exception using --install-os]

### ISSUE THREAD

**Issue by cswanda** [home-assistant/home-assistant.io#629]
Very newbie here....

nmap_tracker only works when I run hass --open-ui.  When trying to run it as a service it throws the below exception.  

`Nmap version 7.12 ( https://nmap.org )
Platform: x86_64-apple-darwin13.4.0
Compiled with: liblua-5.2.4 openssl-1.0.2g nmap-libpcre-7.6 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: kqueue poll select`

`hass --version
0.23.1`

`16-07-09 10:08:15 homeassistant.components.device_tracker: Error setting up platform nmap_tracker
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/components/device_tracker/__init__.py", line 124, in setup_platform
    scanner = platform.get_scanner(hass, {DOMAIN: p_config})
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/components/device_tracker/nmap_tracker.py", line 36, in get_scanner
    scanner = NmapDeviceScanner(config[DOMAIN])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/components/device_tracker/nmap_tracker.py", line 66, in __init__
    self.success_init = self._update_info()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 289, in wrapper
    result = method(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/components/device_tracker/nmap_tracker.py", line 121, in _update_info
    mac = info['addresses'].get('mac') or _arp(ipv4)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/homeassistant/components/device_tracker/nmap_tracker.py", line 46, in _arp
    arp = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'arp'`

**Comment by fabaff** [comment]
This tracker is issue with the documentation:

The output tells your what's wrong: `FileNotFoundError: [Errno 2] No such file or directory: 'arp'`

- https://github.com/home-assistant/home-assistant/issues/1632

**Comment by cswanda** [comment]
Thank you.  I searched and did not see this issue posted anywhere.


On Sat, Jul 9, 2016 at 11:30 AM Fabian Affolter <notifications@github.com>
wrote:

> Closed #629
> <https://github.com/home-assistant/home-assistant.io/issues/629>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/home-assistant/home-assistant.io/issues/629#event-717822830>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APv51SdAXn3mG_Yp91MNSSJ7PAfUg_ceks5qT8y3gaJpZM4JIotQ>
> .
>
-- 


[image: --]

Chris Swanda
[image: https://]about.me/chrisswanda
<https://about.me/chrisswanda?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by ViperRNMC** [comment]
see https://github.com/home-assistant/home-assistant/issues/1632
